### ISSUE TITLE
Arming/disarming does not update area for certain users/configurations

### ISSUE THREAD

**Issue by Chetic** [pyspcwebgw/pyspcwebgw#2] opened 2019-02-28 10:13 UTC
Not sure where this becomes a Home Assistant problem or where it is a pyspcwebgw problem but I'd love to create a pull request if I could get some help understanding the code.
Issue is described here:
https://github.com/home-assistant/home-assistant/issues/21490

**Comment by crallian** [comment] 2020-01-30 08:56
I also have this problem, and think I am making some progress. I have commented in the issue linked by Chetic above.

**Comment by mbrrg** [comment] 2020-10-07 20:39
Closed here as any fix only concerns the HA integration.

**Comment by mbrrg** [comment] 2020-10-07 20:40
Or not. :-)

**Comment by crallian** [comment] 2020-10-07 21:27
Hi @mbrrg, I really appticiate the work you have done with this integration! I am also glad to see that you looking into this again. I have been running my fork since februari without issues, and think it solves the issues #2 and #3, if it can be to any help.

**Comment by kharytonov** [comment] 2020-10-18 22:08
Folks, I've looked over the code and it looks like the state is not reflected when Unsetting as Panel returns `OQ` SIA code, which is not listed in supported codes. I've cut #7 to fix it. Could you please review/merge? Thanks

**Comment by crallian** [comment] 2020-10-19 06:05
@kharytonov Do you only get OQ? Because I get OP-OQ when unset from spcconnect, but only OP when unset from the physical panel (MAP).

As I commented in the link in the first message: https://github.com/home-assistant/core/issues/21490:
(but that should probably have been better suited here...)

"spc fw 3.11
Got it working by adding CL and OP to supported sia codes, no if statement to explicitely set the state was needed.
When I unset from spcconnect I get OP - OQ, where I only get OP if unset from MAP.

I also have problems with unregistered ID if user not 1.
The problems with user ID seems to come from the "sia_adress" message, that no longer states the affected Zone ID, but the User ID performing the status change. I have not found a solution to this yet, and can not see any info in the ws message stating the zone.
Edit: One idea could be to loop over all areas, and call update, but in area.py check so that we dont update anything if new state==old state (to not uncorrectly overwrite last changed by...)"
...and this together with the loop over areas suggested is also implemented in my pull request...

**Comment by kharytonov** [comment] 2020-10-19 09:55
@crallian I'm consistently getting 'OQ' when does from the app. I can't (don't know how) easily test when unsetting from the panel. SPC GW web debugger instantly logs "User End" ('ZG') and debugger doesn't show event history.

**Comment by crallian** [comment] 2020-10-19 12:29
> @crallian I'm consistently getting 'OQ' when does from the app. I can't (don't know how) easily test when unsetting from the panel. SPC GW web debugger instantly logs "User End" ('ZG') and debugger doesn't show event history.

Which fw are you using in SPC?

I am on 3.11.0, but got the same results on 3.9.1:
If I Unset in the app, I get both OP (Opening Report) and OQ (Opening Remote).
If I Unset on the MAP/keypad, such as SPCK420, I only get OP (Opening Report).

Unfortunately, OP (and OQ) doesn't provide the Area ID as the already implemented OG (Open Area), but instead the User ID in the same part of the message.
Therefore, just adding OP (or OQ) to the list of supported SIA codes will throw an error unless you only have one Area with ID=1, and only use one User with ID=1.
(and the same goes for the closing commands).

**Comment by kharytonov** [comment] 2020-10-19 20:32
@crallian yeah makes sense what you're saying. It looks like the SIA address field is actually conveying a contextual information based to what entity (area, user etc) an event is triggered for.

I was just thinking, and I do not claim to be an expert here. Since we do know what area we're changing state for, why don't we make a second call to REST API straight after a change_mode call and update a state rather than rely on event messaging? At that time Area ID is known since its passed in by the caller. We can handle all state updates on the spot.

Thoughts?

**Comment by crallian** [comment] 2020-10-19 20:47
> @crallian yeah makes sense what you're saying. It looks like the SIA address field is actually conveying a contextual information based to what entity (area, user etc) an event is triggered for.
> 
> I was just thinking, and I do not claim to be an expert here. Since we do know what area we're changing state for, why don't we make a second call to REST API straight after a change_mode call and update a state rather than rely on event messaging? At that time Area ID is known since its passed in by the caller. We can handle all state updates on the spot.
> 
> Thoughts?

I am not an expert att all, but I went the same path half a year ago.

If I remember correctly, what you decribe is more or less how it works, the problem is that CL and OP doesnt provide an Area ID, so my solution is to loop over all areas for that case.

I welcome you to try my fork, which I also posted as a pull request in february. It solves this issue for me, and a few other minor bugs. I have been running my fork without issues since february, and at least one other user tried it and confirmed that it solved the problem.
Unfortunately I have not got any response from mbrrg yet.

**Comment by crallian** [comment] 2023-01-13 23:21
I think this issue should be solved by now, by the merge of PR #10 .

**Comment by jschlyter** [comment] 2023-12-18 06:22
ping @crallian

**Comment by crallian** [comment] 2023-12-27 20:26
> ping @crallian

Yes, please close this issue! =)

**Closed** 2023-12-27 20:59 UTC
